version: "3.3"

networks:
 drupal:
    external: true

services:
  db:
    image: mariadb:latest
    networks:
      - drupal
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: somedrupal
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal

  drupal:
    image: 0lfi/drupal:latest
    networks:
      - drupal
    ports:
      - "8080:80"
    volumes:
      - ./volumes/drupal:/srv/drupal
